### ISSUE TITLE
"Testing Components" guide is broken for Ember-CLI

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/website#2025]
The [Testing Components guide](http://emberjs.com/guides/testing/testing-components/) doesn't work for Ember-CLI applications. Specifically, the integration test helpers aren't defined in a unit test. For example, the guide includes

```js
moduleForComponent('my-foo', 'MyFooComponent');

test('clicking link updates the title', function() {
  var component = this.subject();

  // append the component to the DOM
  this.append();

  // assert default state
  equal(find('h2').text(), "I'm a little teapot");

  // perform click action
  click('button');

  andThen(function() { // wait for async helpers to complete
    equal(find('h2').text(), "I'm a little embereño");
  });
});
```

but when I try to include `click('button')`, I get
```
Died on test #1     at Object.test (http://localhost:7357/assets/test-support.js:1867:13)
    at http://localhost:7357/assets/my-app.js:6443:15
    at requireModule (http://localhost:7357/assets/vendor.js:77:29)
    at Object.TestLoader.loadModules (http://localhost:7357/assets/test-loader.js:21:13)
    at Function.TestLoader.load (http://localhost:7357/assets/test-loader.js:28:24)
    at HTMLDocument.<anonymous> (http://localhost:7357/assets/test-support.js:4884:14)
    at fire (http://localhost:7357/assets/vendor.js:3261:30): click is not defined@ 23 ms
Source: 	
ReferenceError: click is not defined
```

Ported from https://github.com/emberjs/guides/issues/5

**Comment by jamesarosen** [comment]
I needed to add the following to my test to get it to run:

```js
import Ember from "ember";
import startApp from '../../helpers/start-app';

var App;

moduleForComponent('my-foo', 'MyFooComponent', {
  setup: function() {
    App = startApp();
  },
  teardown: function() {
    Ember.run(App, 'destroy');
  }
});
```

Ported from https://github.com/emberjs/guides/issues/5#issuecomment-75276455

**Comment by trek** [comment]
Future guides will reflect ember-cli style, so this will eventually get migrated.
