### ISSUE TITLE
Run Error "website/lib/sponsors.rb:11:in `<module:Helpers>': uninitialized constant Sponsors::Helpers::APIDocs (NameError)"

### ISSUE THREAD

**Issue by ubuntuvim** [emberjs/website#2670]
The following is a detailed error message:
```sh
/home/mywebs/website/lib/sponsors.rb:11:in `<module:Helpers>': uninitialized constant Sponsors::Helpers::APIDocs (NameError)
        from /home/mywebs/website/lib/sponsors.rb:9:in `<module:Sponsors>'
        from /home/mywebs/website/lib/sponsors.rb:1:in `<top (required)>'
        from /home/mywebs/website/config.rb:5:in `require'
        from /home/mywebs/website/config.rb:5:in `block in initialize'
        from /home/mywebs/website/config.rb:5:in `each'
        from /home/mywebs/website/config.rb:5:in `initialize'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:162:in `instance_eval'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:162:in `initialize'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/data.rb:31:in `initialize'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/application.rb:213:in `initialize'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:56:in `new'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:56:in `inst'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:132:in `new_app'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:31:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/cli/server.rb:89:in `server'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:72:in `method_missing'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:20:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/middleman-core-3.4.1/bin/middleman:18:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/middleman:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/middleman:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

This is my system and operating environment.

```sh
root@iZ94y0fi6qfZ:/home/mywebs/website# cat /etc/issue
Ubuntu 12.04.5 LTS \n \l

root@iZ94y0fi6qfZ:/home/mywebs/website# ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

root@iZ94y0fi6qfZ:/home/mywebs/website# gem -v
2.5.1

root@iZ94y0fi6qfZ:/home/mywebs/website# rvm -v
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```

Do not know if I have encountered this problem, I ask how to solve, I find Google does not know how to solve.  

Looking forward to your reply.

**Comment by acorncom** [comment]
@ubuntuvim Are you available to discuss on the Ember Community Slack?  If so, please visit `#-team-learning` and we can see about helping you debug ...

**Comment by ubuntuvim** [comment]
@acorncom Thanks for reminding.

**Comment by ubuntuvim** [comment]
I was negligent, with non root permissions to run on it.
