### ISSUE TITLE
Error when checking documentation for rsvp

### ISSUE THREAD

**Issue by paulcwatts** [emberjs/website#3206]
Reproduction:

1. Go to https://emberjs.com/api/ember/release/modules/rsvp
1. Click on any of the functions in 'rsvp' (all, allSettled, etc.)

You get the "WHOOPS! SOMETHING WENT WRONG." page. There are two errors in the console:

```
GET https://ember-api-docs.global.ssl.fastly.net/json-docs/ember/3.0.0/classes/undefined.json 404 (Not Found) 

Error while processing route: project-version.functions.function Unexpected token < in JSON at position 0 SyntaxError: Unexpected token < in JSON at position 0
    at parse (<anonymous>)
    at h (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-99e315d293d3994401805b0617678cc6.js:3335:27)
    at A (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-99e315d293d3994401805b0617678cc6.js:3342:9)
    at O (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-99e315d293d3994401805b0617678cc6.js:3340:43)
    at e.invoke (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-99e315d293d3994401805b0617678cc6.js:1309:145)
    at e.flush (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-99e315d293d3994401805b0617678cc6.js:1296:172)
    at e.flush (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-99e315d293d3994401805b0617678cc6.js:1312:15)
    at e.end (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-99e315d293d3994401805b0617678cc6.js:1320:9)
    at _boundAutorunEnd (https://ember-api-docs-frontend.global.ssl.fastly.net/assets/vendor-99e315d293d3994401805b0617678cc6.js:1316:388)
```

**Comment by jenweber** [comment]
Hiya @paulcwatts, thanks for taking the time to alert us to this issue! It will be fixed in the api docs repo https://github.com/ember-learn/ember-api-docs

Closed, tracked in https://github.com/ember-learn/ember-api-docs/issues/459
